# Generated by Django 3.1.4 on 2023-11-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0002_logitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flightlogitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tach', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=2000)),
            ],
        ),
    ]
