# Generated by Django 3.1.4 on 2023-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0003_flightlogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlogitem',
            name='hours',
            field=models.CharField(default='1.25', max_length=5),
            preserve_default=False,
        ),
    ]
