# Generated by Django 3.1.4 on 2023-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0004_flightlogitem_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlogitem',
            name='fuel',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
