# Generated by Django 3.1.4 on 2023-11-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0006_auto_20231125_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintlogitem',
            name='logitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flynote.logitem'),
            preserve_default=False,
        ),
    ]
