# Generated by Django 3.1.4 on 2023-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0009_maintlogitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintlogitem',
            name='annual_finished',
            field=models.BooleanField(default=False),
        ),
    ]
