# Generated by Django 3.1.4 on 2023-11-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0010_maintlogitem_annual_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('k_id', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Airfield_to_uta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.airfield')),
                ('uta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flynote.user_to_aircraft')),
            ],
        ),
    ]
