# Generated by Django 3.1.4 on 2023-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0012_wandb_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wandb_item',
            name='arm',
            field=models.FloatField(),
        ),
    ]
