# Generated by Django 3.1.4 on 2023-11-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0013_auto_20231126_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wandb_item',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='wandb_item',
            name='arm',
        ),
        migrations.CreateModel(
            name='wandb_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('arm', models.FloatField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='wandb_item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flynote.wandb_category'),
            preserve_default=False,
        ),
    ]
