# Generated by Django 3.1.4 on 2023-11-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0015_ac_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_item',
            name='value',
        ),
        migrations.CreateModel(
            name='Ac_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('ac_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.ac_item')),
            ],
        ),
    ]
