# Generated by Django 3.1.4 on 2023-11-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0016_auto_20231126_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ac_item',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.ac_category'),
        ),
    ]
