# Generated by Django 3.1.4 on 2023-12-14 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0018_auto_20231126_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
            preserve_default=False,
        ),
    ]
