# Generated by Django 3.1.4 on 2023-12-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0019_logitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('superseded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flynote.ad')),
            ],
        ),
        migrations.CreateModel(
            name='AD_aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_tach', models.FloatField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('complied', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.ad')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.aircraft')),
                ('compliance_log_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flynote.maintlogitem')),
            ],
        ),
    ]
