# Generated by Django 3.1.4 on 2023-12-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0020_ad_ad_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_aircraft',
            name='note',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
