# Generated by Django 3.1.4 on 2023-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0021_ad_aircraft_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_aircraft',
            name='applicable',
            field=models.BooleanField(default=True),
        ),
    ]
