# Generated by Django 3.1.4 on 2023-12-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0022_ad_aircraft_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flynote.ad'),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='applicable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='compliance_log_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flynote.maintlogitem'),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='complied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='due_tach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='note',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ad_aircraft',
            name='recurring',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Ada_maintitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=400)),
                ('ada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.ad_aircraft')),
                ('maintitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.maintlogitem')),
            ],
        ),
    ]
