# Generated by Django 3.1.4 on 2023-12-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0023_auto_20231227_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rel_path', models.CharField(max_length=400)),
            ],
        ),
    ]
