# Generated by Django 3.1.4 on 2024-01-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0025_maintitem_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tach_adjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('firstlog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flynote.maintlogitem')),
            ],
        ),
    ]
