# Generated by Django 3.1.4 on 2024-01-26 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0026_tach_adjust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.ac_item')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.file')),
            ],
        ),
    ]
