# Generated by Django 3.1.4 on 2024-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0027_ac_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='wandb_box_segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cg', models.FloatField()),
                ('max_cg', models.FloatField()),
                ('gross_weight', models.IntegerField()),
            ],
        ),
    ]
