# Generated by Django 3.1.4 on 2024-01-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0028_wandb_box_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wandb_box_segment',
            name='aircraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flynote.aircraft'),
            preserve_default=False,
        ),
    ]
