# Generated by Django 3.1.4 on 2024-02-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0029_wandb_box_segment_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield_to_uta',
            name='field_elevation',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfield_to_uta',
            name='pattern_altitude',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.IntegerField()),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flynote.airfield')),
            ],
        ),
    ]
