# Generated by Django 3.1.4 on 2024-02-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flynote', '0032_minimums'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlogitem',
            name='day_landings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flightlogitem',
            name='night_landings',
            field=models.IntegerField(default=0),
        ),
    ]
